### ISSUE TITLE
タイポ修正依頼

### ISSUE THREAD

**Issue by komatzz** [laravel-ja/ja-docs-5.5#1]
## ページ（章）
- https://readouble.com/laravel/5.5/ja/queues.html

## 段落
- `失敗したジョブの再試行`

## 問題のある和文
- `Arisanコマンドを利用します。`

## 正しいと思われる和文
- `Artisanコマンドを利用します。`

## 説明
タイポ修正

**Comment by HiroKws** [comment]
修正しました。ありがとうございます。
