### ISSUE TITLE
タイポ修正依頼

### ISSUE THREAD

**Issue by motuo1201** [laravel-ja/ja-docs-5.5#12]
[Laravel 5.5 Bladeテンプレート](https://readouble.com/laravel/5.5/ja/blade.html)ページの「レイアウト拡張」で、出だしが「子のページを定義するには、」になっています。(「この」ページが正しいかと思います)

**Comment by HiroKws** [comment]
子供の子です。レイアウトが親、それを利用する拡張側のビューは子にあたるため、子と訳しています。原文はchildです。

**Comment by motuo1201** [comment]
理解できました。失礼しました。
ありがとうございます。

**Comment by HiroKws** [comment]
いえいえ、ご指摘ありがとうございます。

本当に「この」が「子の」になっていた部分もかつてありましたので、気になる部分がありましたら、またご指摘ください。
