### ISSUE TITLE
タイポ修正依頼

### ISSUE THREAD

**Issue by PiroHiroPiro** [laravel-ja/ja-docs-5.5#14]
ページ : https://readouble.com/laravel/5.5/ja/session.html

## cookieの「セッション」が「セション」に
- 設定の部分
<img width="808" alt="2017-12-17 22 11 54" src="https://user-images.githubusercontent.com/15605155/34079765-5b630d72-e377-11e7-8093-48b12c8055a2.png">

## 「Redis」が「Reids」に
- ドライバの事前要件のRedis部分
<img width="859" alt="2017-12-17 22 11 46" src="https://user-images.githubusercontent.com/15605155/34079766-5cf202b0-e377-11e7-9dd1-b0f4c71c6b46.png">

**Comment by HiroKws** [comment]
ありがとうございます。次の修正タイミングでリポジトリの内容に反映します。その他の修正を合わせ、まとめてreadouble.comへ公開します。
