### ISSUE TITLE
タイポ修正依頼

### ISSUE THREAD

**Issue by hotta** [laravel-ja/ja-docs-5.5#16]
https://readouble.com/laravel/5.5/ja/structure.html

s/make:mall/make:mail/ かと思います。

**Comment by mogami74** [comment]
https://readouble.com/laravel/5.5/ja/database.html
クエリイベントのリッスン

> アプリケーションで実行される各SQLクエリを取得したい場合は、listenメソッドがし良いうできます。

「listenメソッドが使用できます」だと思います

**Comment by HiroKws** [comment]
ありがとうございます。リポジトリ上のファイルを修正しました。readouble.comへの反映は、次回の翻訳内容反映時に過去の指摘事項の反映を含め、一度に行います。しばらくお待ちください。
