### ISSUE TITLE
翻訳抜け

### ISSUE THREAD

**Issue by hotta** [laravel-ja/ja-docs-5.5#19]
https://readouble.com/laravel/5.5/ja/facades.html#real-time-facades

誤）インポートするクラスのプレフィックス
正）インポートするクラスの名前空間のプレフィックス

原文は以下の通りです：
https://laravel.com/docs/5.5/facades#real-time-facades
To generate a real-time facade, simply prefix the namespace of the imported class with  Facades:

**Comment by HiroKws** [comment]
ありがとうございます。実は最初はご指摘の通り訳したのですが、修飾がしつこいため、あえて名前空間を外しました。プログラミング言語で「インポート」とは、クラスやライブラリを使用できるように宣言することですが、たいてい階層化した指定方法があり、PHPの場合は名前空間です。

つまり、インポートする時点でクラスを修飾するのは名前空間ですから、プレフィックス（事前修飾子）としてクラスにつけるのは文脈的に名前空間だからです。

ただ、クラス名に文字列をプレフィックスとしてつけると誤解される可能性がありますので、以下のように変更したいと思います。

「インポートするクラスのプレフィックスとして、`Facade`名前空間を付けるだけです。」

readouble.comの翻訳へは、他の修正や原文変更と一緒に行うため、しばらくお待ちください。
