### ISSUE TITLE
タイポ修正依頼

### ISSUE THREAD

**Issue by pinekta** [laravel-ja/ja-docs-5.5#2]
## 該当箇所

ページフッタの
```
誤訳・タイポ・翻訳抜けなどの報告は、GitHabリポのIssueで報告してください。
```
ですが、
`GitHab`ではなく`GitHub`です。

マニュアルの本文と関係はありませんが、気になりましたのでよろしくおねがいします:pray:

**Comment by HiroKws** [comment]
ありがとうございました。 反映しました。
