### ISSUE TITLE
Cache のカナ表記揺れ

### ISSUE THREAD

**Issue by gotoeveryone** [laravel-ja/ja-docs-5.5#21]
https://readouble.com/laravel/5.5/ja/cache.html

`Cache`のカナ表記について、以下が混在しています。

- キャシュ
- キャッシュ

意図されていないのであれば、「ドキュメント章別ページ」にある「キャッシュ」で統一したほうが良いかと思います。

**Comment by HiroKws** [comment]
ありがとうございます。キャシュがタイポです。キャッシュに統一いたします。

readouble.comへの反映は、原文変更を和文に取り込むタイミングとなりますので、しばらくお待ちください。
