### ISSUE TITLE
タイポ修正依頼

### ISSUE THREAD

**Issue by motuo1201** [laravel-ja/ja-docs-5.5#23]
ページ
## Laravel 5.5 サービスコンテナ
https://readouble.com/laravel/5.5/ja/container.html

場所
####  タグ付け

×それらをtag**メソッ**でタグ付けすることができます。
〇それらをtag**メソッド**でタグ付けすることができます。

**Comment by HiroKws** [comment]
ありがとうございます。readouble.comへの修正は、次回原文の変更点を和文へ適用する時点で、同時に公開いたします。
