### ISSUE TITLE
タイポ修正依頼

### ISSUE THREAD

**Issue by Masa-Shin** [laravel-ja/ja-docs-5.5#28]
「Laravel 5.5 認証」ページ（ https://readouble.com/laravel/5.5/ja/authentication.html ）
の「データベースの検討事項」節の一行目、「と」の文字が重複していました。

×デフォルトととしてLaravelは ⇒  〇デフォルトとしてLaravelは

**Comment by HiroKws** [comment]
ありがとうございます。readouble.comへの反映は、次回の原文の変更を訳した後、一緒に公開します。
