### ISSUE TITLE
タイポ修正依頼

### ISSUE THREAD

**Issue by Masa-Shin** [laravel-ja/ja-docs-5.5#29]
「ルーティング」ページ（ https://readouble.com/laravel/5.5/ja/routing.html ）の「擬似フォームメソッド」の一行目、
「HTML」が「HTLM」になっていました。細かいですが一応報告します。

**Comment by HiroKws** [comment]
ありがとうございます。readouble.comへの反映は、次回の原文の変更を訳した後、一緒に公開します。
