### ISSUE TITLE
例示されているcomposer.jsonの文字列内の'\'がエスケープされていません

### ISSUE THREAD

**Issue by crhg** [laravel-ja/ja-docs-5.5#32]
「Laravel 5.5 アップグレードガイド」(https://readouble.com/laravel/5.5/ja/upgrade.html) の「依存パッケージのアップデート」のところに、composer.jsonへ追加する設定の記述がありますが、その中の文字列に含まれる`\`がエスケープされていないのでそのままコピペで取り込んだらcomposerの実行時にエラーになりました。英語版ではエスケープされていてこちらだと問題ありませんでした。

日本語版:
```
"scripts": [
    ...
    "post-autoload-dump": [
        "Illuminate\Foundation\ComposerScripts::postAutoloadDump",
        "@php artisan package:discover"
    ],
}
```

該当箇所の英語版:
```
"scripts": {
    ...
    "post-autoload-dump": [
        "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
        "@php artisan package:discover"
    ],
}
```

**Comment by HiroKws** [comment]
ありがとうございます。readouble.comへの修正は、原文の更新を反映する時点で同時に公開いたします。
