### ISSUE TITLE
トップページのリンクが全て404

### ISSUE THREAD

**Issue by hidekuro** [laravel-ja/ja-docs-5.5#35]
すべてのバージョンで共通ですが、トップページからのリンクが切れているのは意図したものでしょうか。

例えば最新5.5の場合、 https://readouble.com/laravel/5.3/ja/ からのページリンクが全て404です。
左上の📙アイコンからのリンクは全て生きています。

- 404: https://readouble.com/docs/5.5/releases
- alive: https://readouble.com/laravel/5.5/ja/releases.html

パスが違うようですが。

**Comment by HiroKws** [comment]
しばらく前に気が付きましたが、修正はまだしていません。readouble.comは個別ページへのアクセスがメインで、tocページへのアクセスはほぼありません。

PHPのバージョンアップ時にサーバーを載せ替えた際の設定を変更したのが原因ですが、アクセスが少ないため、そのうちに修正します。（たぶん、PHPを7.1かそれ以上に上げる時点です。さほど遠くない将来です。）

**Comment by HiroKws** [comment]
サーバーサイドの設定ではなく、laravel/バージョン/言語レベルのindex.htmlを現状のTOCに変更したときに入り込んだバグでした。修正いたしました。

生成スクリプトのバグですので、翻訳とは関係ないため、このリポジトリの内容に変更はありません。
