### ISSUE TITLE
誤訳の修正

### ISSUE THREAD

**Issue by musou1500** [laravel-ja/ja-docs-5.5#38]
Laravel 5.5 アセットのコンパイル(Laravel Mix) の ベンダの抽出の章について
https://readouble.com/laravel/5.5/ja/mix.html#vendor-extraction

以下の文章について，
> 全ベンダーライブラリーをアプリケーション固有のJavaScriptとして結合することにより、発生する可能性がある欠点は、長期間のキャッシュが効きづらくなることです。

原文には
> One potential downside to bundling all application-specific JavaScript with your vendor libraries is that it makes long-term caching more difficult. 

とあります．

* "all"は"application-specific JavaScript"にかかっているのではないでしょうか
* with your vendor librariesとあるので，「全ベンダーライブラリーと」となるのではないでしょうか

修正後の訳として
> 全てのアプリケーション固有のJavaScriptとベンダーライブラリを結合することにより

を提案させていただきます．

**Comment by HiroKws** [comment]
提案を取り入れさせて頂きました。ありがとうございます。
