### ISSUE TITLE
アップグレードガイドのArtisan部分の誤訳

### ISSUE THREAD

**Issue by harunbu** [laravel-ja/ja-docs-5.5#39]
https://github.com/laravel-ja/ja-docs-5.5/blob/master/translation-ja/upgrade.md
アップグレードガイド > Artisan > コマンドのオートロード
現状だと、どのメソッドに行を追加して良いのか、わかりにくくなってます。
原文を読むと、`commands`メソッドの中に行を追加しろと読み取れるので、修正を提案します。

【該当箇所】
> この新機能を利用するには、`App\Console\Kernel`クラスへ以下のように、`commands`メソッドを追加してください。（訳注：loadメソッドの間違い）

【修正案】
> この新機能を利用するには、以下の行を`App\Console\Kernel`クラスの`commands`メソッドに追加してください。

【原文】
> To take advantage of this new feature, you should add the following line to the commands method of your App\Console\Kernel class:

**Comment by HiroKws** [comment]
ありがとうございます。readouble.comへの反映は、原文の更新を反映するタイミングで一緒に行います。しばらく、お待ちください。
