### ISSUE TITLE
フッターのtypo

### ISSUE THREAD

**Issue by tyokinuhata** [laravel-ja/ja-docs-5.5#4]
タイポの報告を促す文中で、"GitHub"を"GitHab"にタイポしている。

<img width="692" alt="2017-11-07 0 19 36" src="https://user-images.githubusercontent.com/16177316/32448302-e9fafb80-c351-11e7-92a2-578da68af450.png">

**Comment by HiroKws** [comment]
ありがとうございます。修正を反映しました。
