### ISSUE TITLE
Passportまわりの訳について

### ISSUE THREAD

**Issue by hidekuro** [laravel-ja/ja-docs-5.5#40]
"Authorization code" を「認証コード」と訳されていますが、AuthorizationであってAuthenticationではないので、「認可コード」かと思います。認証と認可は無視できない意味の違いがあります。

用語についてはこちらも参照して下さい。 https://openid-foundation-japan.github.io/rfc6749.ja.html

**Comment by HiroKws** [comment]
ありがとうございます。Authorization codeは、認証コード、認可コードと訳している部分がありました。認証コード（2箇所、１行）は誤訳として、認可コードへ修正しました。

せっかくリンクを貼っていただきましたが、私はWeb上の認証技術を完全に理解する意図は持っておりません。作業の効率化のため、翻訳作業として、ただ機械的にauthorizationは認可と訳すだけに留めています。あしからず、ご了承ください。

仮に原文の用語がそぐわない部分を見つけた場合は、原文のリポジトリへ修正プルリクをお願いします。

**Comment by HiroKws** [comment]
readouble.comへの修正には、多少時間がかかります。
