### ISSUE TITLE
「シーディング」ページのリンクについて

### ISSUE THREAD

**Issue by dyoshikawa** [laravel-ja/ja-docs-5.5#42]
https://readouble.com/laravel/5.5/ja/seeding.html
上記「シーディング」ページの「モデルファクトリの利用」項目において、「モデルファクトリ」及び「モデルファクトリのドキュメント」のリンク先が誤っているように思うので、修正を提案します。

### 現行リンク先
https://readouble.com/laravel/5.5/ja/testing.html#writing-factories

### 提案リンク先
https://readouble.com/laravel/5.5/ja/database-testing.html#writing-factories

なお、現在翻訳中の5.6日本語ドキュメントも同じ状態であることを確認しています。

**Comment by HiroKws** [comment]
ご指摘ありがとうございます。見落としていたため、対応が遅れてすいません。
