### ISSUE TITLE
ヘルパページのcsrf_token()

### ISSUE THREAD

**Issue by ghost** [laravel-ja/ja-docs-5.5#44]
https://readouble.com/laravel/5.5/ja/helpers.html#method-csrf-token

上のcsrf_fieldと同じ文になっています(5.6も同じになっていました)。
訳は
`csrf_token` 関数は現在のCSRFトークン値を取得します。
あたりでしょうか。

**Comment by HiroKws** [comment]
ありがとうございました。readouble.comへ反映作業中です。すぐに、反映されます。
