### ISSUE TITLE
apiの認可を実装しようとしたら失敗。

### ISSUE THREAD

**Issue by garchomp-game** [laravel-ja/ja-docs-5.5#46]
Your requirements could not be resolved to an installable set of packages.
というエラーが出て、これをどう解決したらいいか全くわかりませんでした。
最終的には
https://github.com/laravel/passport/issues/774
こちらのgithubのissueが参考になり、composer require paragonie/random_compat:2.*を前もってやっておくことで解決しました。
つきまして、ドキュメントの
https://readouble.com/laravel/5.5/ja/passport.html
こちらのインストールには

composer require paragonie/random_compat:2.*
composer require laravel/passport=~4.0
といったような感じで、random_compatの部分を追加してほしいですm(_ _)m

**Comment by HiroKws** [comment]
翻訳リポジトリです。オリジナルを元に翻訳しており、その内容に独自に説明は付け加えません。

オリジナルに対し、要望なり、変更なりを依頼してください。
