### ISSUE TITLE
リンク切れ（MIMEタイプと対応する拡張子の完全なリスト）

### ISSUE THREAD

**Issue by sh-ogawa** [laravel-ja/ja-docs-5.5#8]
[ 対象ページ ]
https://readouble.com/laravel/5.5/ja/validation.html

「mimesルールの基本的な使用法」の項
以下がリンク切れになっています。
誤） https://svn.apache.org/repos/asf/httpd/httpd/trunkmime.types.html
正） https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types

参照元：https://laravel.com/docs/5.5/validation

**Comment by HiroKws** [comment]
ありがとうございます。次回の更新時にreadouble.comへ反映いたします。

**Comment by HiroKws** [comment]
これは、ドキュメントのリンク間違いではなく、readouble.com用にHTMLへ変換しているスクリプトのバグでした。日本語markdownファイルの間違いではないため、一度クローズします。
